<?php

/**
 * @file
 * Contains mobile_number_login_otp.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;

/**
 * Implements hook_help().
 */
function mobile_number_login_otp_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mobile_number_login_otp':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Mobile Number Login OTP module provides a suite of modules containing fun for module developers. For more information, see the <a href=":url">online documentation for the Mobile Number Login OTP module</a>.', [':url' => 'https://www.drupal.org/docs/contributed-modules/mobile-number-login-otp']) . '</p>';
      return $output;
  }
}

/**
 * Implements hook_form_alter().
 */
function mobile_number_login_otp_form_alter(&$form, FormStateInterface $formState, $formId) {
  if ($formId == 'user_login_form') {
    $form['otplink'] = Link::createFromRoute(t('Login with OTP'), 'mobileloginotp.account.login')->toRenderable();
    $form['otplink']['#attributes']['class'][] = 'button button--primary otp-button';
    $form['otplink']['#weight'] = 50;
  }
}
